apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: book-frontend
  # REQUIRED: NodePort to expose the UI externally
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80         # Internal service port
      targetPort: 80   # Port on the Nginx container
      # NodePort will be automatically assigned (e.g., 30000-32767)